
SELECT * FROM(SELECT DISTINCT T1.MODIFIED_AT AS COL_INPUT_DATE,
       T1.PAYMENT_FORM_NO AS COL_PAYMENT_FORM_NO,
       T1.SUPPLIER_CODE AS COL_SUPPLIER_CODE,
       T3.SUPPLIER_NAME AS COL_SUPPLIER_NAME,
       ' ' AS COL_INVOICE_NO,
       ' ' AS COL_PROGRAMME_NO,
       ' ' AS COL_PROGRAMME_NAME,
       ' ' AS COL_PO_NO,
       0 AS COL_FROM_EPISODE_NO, 
       0 AS COL_TO_EPISODE_NO,
       ' ' AS COL_PARTICULARS,
       ' ' AS COL_JOB_DESCRIPTION, 
       ' ' AS COL_AC,
        0  AS COL_PAYMENT_AMOUNT,
       ' ' AS COL_SUB_SECTION,
       T1.MODIFIED_BY  AS COL_MODIFIED_BY,
       ' ' AS COL_WK, 
       ' ' AS COL_MTH
FROM ARC_PAYMENT_REQUEST T1,
     ARC_PAYMENT_DETAILS T2,
     ARC_SUPPLIER        T3
WHERE  T1.MODIFIED_AT BETWEEN '%s' AND '%s'
   AND T1.MODIFIED_BY     = '%s'
   AND T1.PAYMENT_FORM_NO >= '%s' AND T1.PAYMENT_FORM_NO <= '%s'
   AND T1.SUPPLIER_CODE   = T3.SUPPLIER_CODE
   AND T1.SECTION_ID      = '08'                  
   AND T1.PAYMENT_FORM_NO NOT IN(SELECT T2.PAYMENT_FORM_NO FROM ARC_PAYMENT_DETAILS T2)
UNION
SELECT T1.MODIFIED_AT,
       T1.PAYMENT_FORM_NO,
       T1.SUPPLIER_CODE,
       T3.SUPPLIER_NAME,
       T2.INVOICE_NO,
       T2.PROGRAMME_NO,
       T4.PROGRAMME_NAME,
       T2.PURCHASE_ORDER_NO,
       T2.FROM_EPISODE_NO, 
       T2.TO_EPISODE_NO,
       T2.PARTICULARS,
       T2.JOB_DESCRIPTION, 
       T2.ACCOUNT_ALLOCATION || '-' || T5.ACTUAL_ACCOUNT_DESCRIPTION AS COL_AC,
       T2.PAYMENT_AMOUNT,
       T2.SUB_SECTION_ID || '-' || T6.SECTION_NAME AS COL_SUB_SECTION,
       T2.MODIFIED_BY,
       T2.INCLUDE_IN_WEEKLY_REPORTING,
       T2.INCLUDE_IN_MONTHLY_REPORTING
      FROM DEV.ARC_PAYMENT_REQUEST T1,
       ARC_PAYMENT_DETAILS T2,
       ARC_SUPPLIER        T3,
       ARC_PROGRAMME_MASTER T4,
       ARC_ACCOUNT_ALLOCATION T5,
       ARC_SECTION T6
 WHERE  T2.MODIFIED_AT BETWEEN '%s' AND '%s'   
    AND T2.MODIFIED_BY     = '%s'
	AND	T1.PAYMENT_FORM_NO = T2.PAYMENT_FORM_NO
	AND T2.PAYMENT_FORM_NO >= '%s' AND T2.PAYMENT_FORM_NO <= '%s'
	AND	T1.SECTION_ID      = '08'               
	AND	T6.SECTION_ID      = '08'              
	AND	T2.SUB_SECTION_ID  = T6.SUB_SECTION_ID   
	AND	T1.SUPPLIER_CODE   = T3.SUPPLIER_CODE   
	AND T2.PROGRAMME_NO    = T4.PROGRAMME_NO    
	AND	T2.ACCOUNT_ALLOCATION   = T5.ACTUAL_ACCOUNT_ALLOCATION )
 ORDER BY 1,2

		